Part 12
BrovkinOleg/Pro_RoR pull request #10
Opened 2020-01-10 14:07 UTC by BrovkinOleg

part_12 compare with master

2020-01-11 10:06 UTC, vkurennov requested changes

2020-01-11 10:06 UTC, vkurennov commented on app/models/user.rb
> +  def self.find_by_auth(auth)
а где тесты модели на этот  и последующие методы?

2020-01-11 10:06 UTC, BrovkinOleg commented
Получено письмо на  Yandex

2020-01-12 11:11 UTC, vkurennov approved these changes

2020-01-12 12:59 UTC, merged

2020-01-29 13:17 UTC, BrovkinOleg commented
Виталий, здравствуйте. Мне не открывается 17-ая тема (16 - Sphinx, принята).Помогайте, времени мало. 12.01.2020, 14:11, "Vitaly Kurennov" <notifications@github.com>:@vkurennov approved this pull request.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  С Уважением, Бровкин О.Ю. 