Part 06
BrovkinOleg/Pro_RoR pull request #3
Opened 2019-11-07 14:12 UTC by BrovkinOleg

Compare part_06 with master.

2019-11-07 19:57 UTC, aishek requested changes

2019-11-07 19:57 UTC, aishek commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
Ещё нужны тесты ассоциаций

2019-11-07 19:57 UTC, aishek commented on app/models/answer.rb
> +  belongs_to :user
На это нужен тест

2019-11-07 19:57 UTC, aishek commented on app/models/question.rb
> +  belongs_to :user
На это нужен тест

2019-11-07 19:57 UTC, aishek commented on app/views/answers/new.html.slim
> +p = render 'shared/footer', local: true
Форма просится в партиал

2019-11-07 19:57 UTC, aishek commented on app/views/questions/show.html.slim
> +    p = f.submit 'Create'
Форма просится в партиал

2019-11-07 19:57 UTC, aishek commented on app/views/questions/show.html.slim
> +    p= link_to 'Delete answer', question_answers_path(@question) + "/#{answer.id}", method: :delete
Тут хочется написать `= render @question.answers`

2019-11-07 19:57 UTC, aishek commented on app/views/questions/index.html.slim
> +  a href="/questions/#{question.id}" = question.title
Тут хочется написать `= render @questions`

2019-11-07 19:57 UTC, aishek commented on spec/features/answers/create_answer_spec.rb
> +    click_on question.title
Это можно в `background`, и можно сократить до логина и посещения страницы вопроса

2019-11-07 19:57 UTC, aishek commented on spec/features/answers/create_answer_spec.rb
> +    click_on question.title
Это можно в `background`, и можно сократить до логина и посещения страницы вопроса

2019-11-07 19:57 UTC, aishek commented on spec/features/answers/create_answer_spec.rb
> +    click_on question.title
Лучше сразу посетить страницу вопроса

2019-11-07 19:57 UTC, aishek commented on spec/features/answers/create_answer_spec.rb
> +    expect(page).to have_no_content 'Create answer'
Тут хочется более специфичный селектор: кнопку или ссылку

2019-11-07 19:57 UTC, aishek commented on spec/features/answers/delete_answer_spec.rb
> +    answer
Вместо такого лучше использовать `given!(:answer)`

2019-11-07 19:57 UTC, aishek commented on spec/features/answers/delete_answer_spec.rb
> +    click_on 'Delete answer'
Нужно проверить что до удаления текст вопроса был, а после удаления пропал

2019-11-07 19:57 UTC, aishek commented on spec/features/answers/delete_answer_spec.rb
> +    expect(page).to have_no_content 'Delete answer'
Хочется более специфичный селектор: кнопку или ссылку

2019-11-07 19:57 UTC, aishek commented on spec/features/auth/sign_in_spec.rb
> +  scenario 'Registered user tries to sign in' do
Ещё имеет смысл проверить правильный логин но неправильный пароль

2019-11-07 19:57 UTC, aishek commented on spec/features/auth/sign_out_spec.rb
> +  scenario 'Registered and authorized user try to log out' do
И гостя проверить

2019-11-07 19:57 UTC, aishek commented on spec/support/future_helpers.rb
> +  def sign_up(user)
Этот хелпер не нужен

2019-11-07 19:57 UTC, aishek commented on spec/features/auth/sign_up_spec.rb
> +    sign_up(user)
Лучше код написать-таки тут, смысла в хелпере нет

2019-11-07 19:57 UTC, aishek commented on spec/features/auth/sign_up_spec.rb
> +  scenario 'Registered user try to sign up' do
И пустые поля тоже имеет смысл проверить

2019-11-07 19:57 UTC, aishek commented on spec/features/questions/create_question_spec.rb
> +    expect(page).to have_content 'You need to sign in or sign up before continuing.'
Хочется более специфичный селектор: кнопку или ссылку

2019-11-07 19:57 UTC, aishek commented on spec/features/questions/delete_question_spec.rb
> +    expect(page).to have_no_content question.title
Идеально перед кликом проверить что контент был

2019-11-07 19:57 UTC, aishek commented on spec/features/questions/delete_question_spec.rb
> +    expect(page).to have_no_content 'Delete question'
Хочется более специфичный селектор: кнопку или ссылку

2019-11-07 19:57 UTC, aishek commented on spec/features/questions/delete_question_spec.rb
> +    expect(page).to have_no_content 'Delete question'
Хочется более специфичный селектор: кнопку или ссылку

2019-11-07 19:57 UTC, aishek commented on spec/features/questions/view_questions_spec.rb
> +    click_on question.title
Можно сразу перейти на страницу вопроса

2019-11-07 19:57 UTC, aishek commented on spec/features/questions/view_questions_spec.rb
> +    click_on question.title
Можно сразу перейти на страницу вопроса

2019-11-07 19:57 UTC, aishek commented on app/controllers/answers_controller.rb
> +      redirect_to @question, notice: 'Answer field can not be blank.'
Так ошибки ответа потеряются

2019-11-07 19:57 UTC, aishek commented on app/controllers/answers_controller.rb
> +    if @answer.user_id == current_user.id
Проверку имеет смысл выделить в отдельную абстракцию (функцию) чтобы протестировать её и использовать в других местах

2019-11-07 19:57 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +  before { sign_in(user) }
Гостя тоже нужно проверить

2019-11-07 19:57 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
Хорошо бы проверить что вопрос назначился пользователю

2019-11-07 19:57 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
Надо проверить неавтора и гостя

2019-11-07 19:57 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +  before { sign_in(user) }
Гостя тоже нужно проверить

2019-11-08 05:30 UTC, BrovkinOleg commented on spec/support/future_helpers.rb
> +  def sign_up(user)
Он используется в "sign_up_spec.rb"

2019-11-08 05:33 UTC, BrovkinOleg commented on spec/support/future_helpers.rb
> +  def sign_up(user)
Исправил

2019-11-08 05:33 UTC, BrovkinOleg commented on spec/features/auth/sign_up_spec.rb
> +    sign_up(user)
Исправил

2019-11-08 06:22 UTC, BrovkinOleg commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
Исправил.

2019-11-08 06:24 UTC, BrovkinOleg commented on app/models/answer.rb
> +  belongs_to :user
Добавил.

2019-11-08 06:26 UTC, BrovkinOleg commented on app/models/question.rb
> +  belongs_to :user
Добавил.

2019-11-08 06:57 UTC, BrovkinOleg commented on spec/features/answers/create_answer_spec.rb
> +    click_on question.title
вынес в background и добавил describe

2019-11-08 06:58 UTC, BrovkinOleg commented on spec/features/answers/create_answer_spec.rb
> +    click_on question.title
вынес в background и добавил describe

2019-11-08 07:13 UTC, BrovkinOleg commented on spec/features/answers/create_answer_spec.rb
> +    click_on question.title
Согласен, исправил.

2019-11-08 07:15 UTC, BrovkinOleg commented on spec/features/answers/create_answer_spec.rb
> +    expect(page).to have_no_content 'Create answer'
Исправил на проверку отсутствия кнопки и проверяю наличие текста.

2019-11-08 07:17 UTC, BrovkinOleg commented on spec/features/answers/delete_answer_spec.rb
> +    answer
Согласен, исправил.

2019-11-08 07:20 UTC, BrovkinOleg commented on spec/features/answers/delete_answer_spec.rb
> +    click_on 'Delete answer'
Добавил до удаления проверку текста: expect(page).to have_content 'MyText'

2019-11-08 07:20 UTC, BrovkinOleg commented on spec/features/answers/delete_answer_spec.rb
> +    expect(page).to have_no_content 'Delete answer'
Исправил на кнопку

2019-11-08 07:42 UTC, BrovkinOleg commented on spec/features/auth/sign_in_spec.rb
> +  scenario 'Registered user tries to sign in' do
Добавил.

2019-11-08 07:50 UTC, BrovkinOleg commented on spec/features/auth/sign_out_spec.rb
> +  scenario 'Registered and authorized user try to log out' do
Гостю добавил проверку ссылки на регистрацию.

2019-11-08 08:12 UTC, BrovkinOleg commented on spec/features/auth/sign_up_spec.rb
> +  scenario 'Registered user try to sign up' do
Добавил три проверки.

2019-11-08 08:23 UTC, BrovkinOleg commented on spec/features/questions/create_question_spec.rb
> +    expect(page).to have_content 'You need to sign in or sign up before continuing.'
Добавил проверку двух линков

2019-11-08 08:26 UTC, BrovkinOleg commented on spec/features/questions/delete_question_spec.rb
> +    expect(page).to have_no_content question.title
Добавил.

2019-11-08 08:28 UTC, BrovkinOleg commented on spec/features/questions/delete_question_spec.rb
> +    expect(page).to have_no_content 'Delete question'
Исправил на have_no_link

2019-11-08 08:30 UTC, BrovkinOleg commented on spec/features/questions/delete_question_spec.rb
> +    expect(page).to have_no_content 'Delete question'
Исправил на link

2019-11-08 08:33 UTC, BrovkinOleg commented on spec/features/questions/view_questions_spec.rb
> +    click_on question.title
Исправил.

2019-11-08 08:37 UTC, BrovkinOleg commented on app/controllers/answers_controller.rb
> +    if @answer.user_id == current_user.id
добавил check_id?

2019-11-08 09:51 UTC, BrovkinOleg commented on spec/controllers/questions_controller_spec.rb
> +  before { sign_in(user) }
Добавил.

2019-11-08 10:14 UTC, BrovkinOleg commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
Гостя и неавтора проверил.

2019-11-08 11:34 UTC, BrovkinOleg commented on spec/controllers/answers_controller_spec.rb
> +  before { sign_in(user) }
Добавил.

2019-11-08 11:44 UTC, BrovkinOleg commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
Добавил expect(question.user_id).to eq user.id

2019-11-08 11:46 UTC, BrovkinOleg commented on spec/features/questions/view_questions_spec.rb
> +    click_on question.title
Исправил

2019-11-08 12:23 UTC, BrovkinOleg commented on app/controllers/answers_controller.rb
> +      redirect_to @question, notice: 'Answer field can not be blank.'
Исправил.

2019-11-08 12:48 UTC, BrovkinOleg commented on app/views/answers/new.html.slim
> +p = render 'shared/footer', local: true
ОК.

2019-11-08 12:50 UTC, BrovkinOleg commented on app/views/questions/show.html.slim
> +    p = f.submit 'Create'
ОК.

2019-11-08 13:26 UTC, BrovkinOleg commented on app/views/questions/index.html.slim
> +  a href="/questions/#{question.id}" = question.title
render не получилось, немного поправил.

2019-11-08 13:27 UTC, BrovkinOleg commented on app/views/questions/show.html.slim
> +    p= link_to 'Delete answer', question_answers_path(@question) + "/#{answer.id}", method: :delete
render не получилось, немного поправил.

2019-11-09 09:12 UTC, aishek requested changes

2019-11-09 09:12 UTC, aishek commented on app/controllers/answers_controller.rb
>        render :new
Тут нужно отрендерить страницу вопроса согласно заданию

2019-11-09 09:12 UTC, aishek commented on app/controllers/answers_controller.rb
> +  end
Функция дублируется для повторного использования. А ведь она ещё и во вьюшках нужна. Что если поместить её в модель пользователя например?

2019-11-09 09:12 UTC, aishek commented on app/views/questions/index.html.slim
> +  p = link_to 'Sign in', new_user_session_path
Это общий для всех страниц код, поэтому лучше отправить его в лайаут

2019-11-09 09:12 UTC, aishek commented on app/views/questions/index.html.slim
> +  p = link_to question.title, question_path(question)
Лучше партиалом всё-таки:

`= render @questions`

```slim
/ Это содержимое файла app/views/questions/_question.html.slim
p = link_to question.title, question_path(question)
```

2019-11-09 09:12 UTC, aishek commented on app/views/questions/show.html.slim
> +- if current_user && @question.user_id == current_user.id
Вот опять метод проверки авторства

2019-11-09 09:12 UTC, aishek commented on app/views/questions/show.html.slim
> +    p = link_to 'Delete answer', question_answer_path(@question, answer.id), method: :delete
Тоже в партиал надо

2019-11-09 09:12 UTC, aishek commented on spec/features/answers/delete_answer_spec.rb
> +    click_on 'Delete answer'
А что пропал после удаления проверить?

2019-11-09 09:12 UTC, aishek commented on spec/features/auth/sign_in_spec.rb
> +  WRONG_PASS = '11111111'
Без констант с просто продублированными строками будет лучше. А если ещё и за неправильный пароль взять строку `wrong password` то будет ещё и читабельнее.

2019-11-09 09:12 UTC, aishek commented on spec/features/auth/sign_out_spec.rb
> +    sign_in(user)
Это надо тоже в `background`

2019-11-09 09:12 UTC, aishek commented on spec/features/auth/sign_out_spec.rb
> +    expect(page).to have_link 'Sign in'
Лучше проверить что кнопки выхода нет

2019-11-09 09:12 UTC, aishek commented on spec/features/questions/create_question_spec.rb
> +    expect(page).to have_no_link 'Sign out'
Надо проверять отсутствие кнопки задания вопроса

2019-11-09 09:12 UTC, aishek commented on spec/features/questions/view_questions_spec.rb
> +feature 'View questions' do
Только в единственном числе

2019-11-09 09:12 UTC, aishek commented on spec/support/future_helpers.rb
> +  end
А этот хелпер где-нибудь используется?

2019-11-09 09:12 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +  describe 'Registered user' do
Лучше тесты разбить по экшенам, а внутри каждого экшена контексты по пользователю написать

2019-11-09 09:12 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +    describe 'author try DELETE #destroy' do
Опечатка?

2019-11-09 09:12 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +  describe 'Unregistered user' do
Тут опять же лучше сначала метод, а в него вложить контексты пользователя

2019-11-09 14:48 UTC, BrovkinOleg commented on app/controllers/answers_controller.rb
>        render :new
На странице вопроса все ответы уже рендерятся в questions/show.html.slim.

2019-11-09 15:08 UTC, BrovkinOleg commented on app/controllers/answers_controller.rb
> +  end
согласен - добавил в модель user

2019-11-09 15:13 UTC, BrovkinOleg commented on app/views/questions/index.html.slim
> +  p = link_to 'Sign in', new_user_session_path
добавил файл "shared/_signed.html.slim"

2019-11-09 15:14 UTC, BrovkinOleg commented on app/views/questions/show.html.slim
> +- if current_user && @question.user_id == current_user.id
ОК.

2019-11-09 15:21 UTC, BrovkinOleg commented on spec/features/auth/sign_in_spec.rb
> +  WRONG_PASS = '11111111'
Исправил.

2019-11-09 15:28 UTC, BrovkinOleg commented on spec/features/auth/sign_out_spec.rb
> +    sign_in(user)
Интересная мысль. Исправил.

2019-11-09 15:37 UTC, BrovkinOleg commented on spec/features/auth/sign_out_spec.rb
> +    expect(page).to have_link 'Sign in'
добавил проверку sign out

2019-11-09 15:42 UTC, BrovkinOleg commented on spec/features/questions/create_question_spec.rb
> +    expect(page).to have_no_link 'Sign out'
Исправил.

2019-11-09 15:45 UTC, BrovkinOleg commented on spec/features/questions/view_questions_spec.rb
> +feature 'View questions' do
ОК.

2019-11-09 15:47 UTC, BrovkinOleg commented on spec/support/future_helpers.rb
> +  end
Не используется - убрал.

2019-11-09 15:58 UTC, BrovkinOleg commented on spec/controllers/answers_controller_spec.rb
> +  describe 'Registered user' do
Исправил.

2019-11-09 16:05 UTC, BrovkinOleg commented on spec/controllers/questions_controller_spec.rb
> +    describe 'author try DELETE #destroy' do
Нет, хотел улучшить читаемость - Исправил.

2019-11-09 16:37 UTC, BrovkinOleg commented on spec/controllers/questions_controller_spec.rb
> +  describe 'Unregistered user' do
Изменил.

2019-11-09 17:42 UTC, BrovkinOleg commented on app/views/questions/index.html.slim
> +  p = link_to question.title, question_path(question)
Исправил.

2019-11-09 18:15 UTC, BrovkinOleg commented on app/views/questions/show.html.slim
> +    p = link_to 'Delete answer', question_answer_path(@question, answer.id), method: :delete
Исправил.

2019-11-11 07:54 UTC, aishek commented on app/controllers/answers_controller.rb
>        render :new
Я про то, что вот эта инструкция рендерит `answers/new`, а должна ведь `questions/show`. Как ведём себя приложение в случае неуспешного создания ответа?

2019-11-11 08:29 UTC, aishek requested changes

2019-11-11 08:29 UTC, aishek commented on app/models/user.rb
> +  def check_id?(object)
Лучше разговаривать в терминах примитивов и вспомогательных структур данных, а в терминах предметной области. Так название "проверить айди?" не о чём не говорит, а название "является ли автором?" не нуждается в дополнительных пояснениях.

2019-11-11 08:29 UTC, aishek commented on app/views/questions/_answer.html.slim
> +p = link_to 'Delete answer', question_answer_path(@question, answer.id), method: :delete
Достаточно `question_answer_path(@question, answer)`

2019-11-11 08:29 UTC, aishek commented on app/views/questions/show.html.slim
> +- if current_user && current_user.check_id?(@question)
Достаточно `- if current_user&.check_id?(@question)`

2019-11-11 08:29 UTC, aishek commented on app/views/questions/show.html.slim
> +- if user_signed_in? && current_user.check_id?(@question)
Зачем эта проверка?

2019-11-11 08:29 UTC, aishek commented on app/views/questions/show.html.slim
> += render partial: 'questions/answer', collection: @question.answers
А такое сработает: `= render @question.answers`

2019-11-11 08:29 UTC, aishek commented on spec/features/questions/view_question_spec.rb
> +  end
Эти тесты лучше объединить

2019-11-11 08:29 UTC, aishek commented on spec/features/questions/view_question_spec.rb
> +  given!(:answer) { create :answer, question: question, user:user }
Идеально создать несколько ответов

2019-11-11 08:29 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +    describe 'Registered user' do
А что с гостем?

2019-11-11 08:29 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +          expect(question.user_id).to eq user.id
Лучше сравнивать объекты а не идентификаторы

2019-11-11 08:29 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +    describe 'Registered user' do
Нужно проверить гостя и не автора

2019-11-12 07:57 UTC, aishek requested changes

2019-11-12 07:57 UTC, aishek commented on app/controllers/answers_controller.rb
>        render :new
Проблема всё ещё не решена.

Нужно проверить, как ведёт себя приложение в таком сценарии:

1. открываем страницу вопроса
2. заполняем форму нового ответа с ошибкой
3. отправляем форму нового ответа

Должно показать ту же страницу, с той же формой и информацией об ошибках.

Сейчас же показывает отдельный шаблон создания ответа.

2019-11-12 07:57 UTC, aishek commented on spec/features/questions/view_question_spec.rb
> +    expect(page).to have_content "text_3"
Неочевидно что это текст ответов, лучше `expect(page).to have_content answer_01.content`

2019-11-12 07:57 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
Блин а почему всё слиплось-то? Надо добавить пустые строки перед каждым `it`

2019-11-12 07:57 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +        expect(question.user).to_not eq not_author
Лучше проверить на соответствие прошлым значениям

2019-11-13 08:02 UTC, aishek requested changes

2019-11-13 08:02 UTC, aishek commented on app/controllers/answers_controller.rb
> +      redirect_to @question, notice: 'Answer field can not be blank.'
Надо исправить

2019-11-13 08:02 UTC, aishek commented on app/controllers/answers_controller.rb
> +    if @answer.update(answer_params)
В задании изменение делать не нужно, но обращаю внимание что тут кто угодно может изменить ответ

2019-11-13 08:02 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +      describe 'not author' do
Для набора условий в тесте лучше использовать `context`. И я не понял почему "неавтор" вложен по отношению к "гостю"

2019-11-13 08:02 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +    describe 'Registered user' do
Должен быть не просто зарегистрированный, а автор

2019-11-13 08:02 UTC, aishek commented on spec/controllers/questions_controller_spec.rb
> +    describe 'Unregistered user' do
И изменение базы тоже нужно проверить

2019-11-13 08:02 UTC, aishek commented on spec/features/questions/view_question_spec.rb
> +    expect(page).to have_content answer_03.body
Лучше циклом. И ещё: чем меньше объектов для теста нужно создать, тем быстрее он проходит. Тут необходимо и достаточно два ответа.

2019-11-13 08:02 UTC, aishek commented on spec/features/questions/view_question_spec.rb
> +  given!(:answer_03) { create :answer, question: question, user:user }
Такое лучше делать через `create_list`

2019-11-14 18:18 UTC, aishek requested changes

2019-11-14 18:18 UTC, aishek commented on app/controllers/answers_controller.rb
> +    redirect_to @question
Это противоречит постановке задачи: "Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)"

2019-11-14 18:18 UTC, aishek commented on app/controllers/answers_controller.rb
> +  #   end
Закомментированный код нужно удалять

2019-11-14 18:18 UTC, aishek commented on spec/features/questions/view_question_spec.rb
> +    expect(page).to have_content answers[1].body
В таких случаях лучше использовать цикл

2019-11-14 18:18 UTC, aishek commented on spec/controllers/answers_controller_spec.rb
> +    context 'Registered user' do
Нужно проверить гостя

2019-11-15 06:17 UTC, aishek requested changes
Всё хорошо, остался последний вопрос с редиректом после создания ответа

2019-11-15 06:17 UTC, aishek commented on app/controllers/answers_controller.rb
> +    render 'questions/show'
А в случае успешного создания нужен-таки редирект. Иначе при попытке обновить страницу мы увидим предупреждение о повторной отправке формы.

2019-11-15 17:02 UTC, aishek approved these changes

2019-11-15 17:10 UTC, merged